### ISSUE TITLE
can someone help me use this on the terminal

### ISSUE THREAD

**Issue by stephan130904** [CoffeSiberian/Download-Spotify-Music-with-YouTubeDL#2]
i normally use yt-dlp with the following command: "yt-dlp URL -P location/" and want to know if it possible to use this program in a similar way or if i have to use the gui

**Comment by CoffeSiberian** [comment]
Unfortunately it is no longer available for terminal use, only using the GUI 😅

**Comment by stephan130904** [comment]
bummer
